Update README.md
Due to ssample code didn't have async with following message:

```
await server.start();
^^^^^

SyntaxError: await is only valid in async functions and the top level bodies of modules
```

So this PR will fix it.

Signed-off-by: NiJia Lin <louis70109@gmail.com>