Fix postgres build
For some reason postgis 2.4 (doesn't exist) tries to get used instead of 2.5.

```
ERROR:  could not access file "$libdir/postgis-2.4": No such file or directory
The command "psql -c 'CREATE EXTENSION postgis;' -U postgres -d 
```